export enum FundTransactionStatus {
  PENDING_TO_BE_SENT = "PENDING_TO_BE_SENT",
  SENT = "SENT",
  RESPONDED = "RESPONDED",
  CANCELED = "CANCELED",
  REJECTED = "REJECTED",
}
export enum FundTransactionType {
  BUY_GROSS = "BUY_GROSS",
  SELL_GROSS = "SELL_GROSS",
  SWITCH_FROM = "SWITCH_FROM",
  SWITCH_TO = "SWITCH_TO",
  REINVESTED_DISTRIBUTION = "REINVESTED_DISTRIBUTION",
  EXTERNAL_TRANSFER_IN = "EXTERNAL_TRANSFER_IN",
  EXTERNAL_TRANSFER_OUT = "EXTERNAL_TRANSFER_OUT",
}
