export enum PlanType {
  UNKNOWN = "UNKNOWN",
  OPEN = "OPEN",
  RRSP = "RRSP",
  RRIF = "RRIF",
  RESP_INDIVIDUAL = "RESP_INDIVIDUAL",
  DPSP = "DPSP",
  LIF = "LIF",
  RHOSP = "RHOSP",
  LIRA = "LIRA",
  OTHER = "OTHER",
  LRIF = "LRIF",
  INSURANCE_MORTGAGE = "INSURANCE_MORTGAGE",
  RESP_FAMILY = "RESP_FAMILY",
  RRTF = "RRTF",
  PRIF = "PRIF",
  DBPP = "DBPP",
  DCPP = "DCPP",
  DUP = "DUP",
  TFSA = "TFSA",
  RDSP = "RDSP",
  RLIF = "RLIF",
  RLSP = "RLSP",
  IPP = "IPP",
}

export enum PlanRecipient {
  UNKNOWN = "UNKNOWN",
  INDIVIDUAL = "INDIVIDUAL",
  SPOUSAL = "SPOUSAL",
  JOINT = "JOINT",
}

export enum PlanAccountDesignation {
  UNKNOWN = "UNKNOWN",
  CLIENT_NAME = "CLIENT_NAME",
  BROKER_NOMINEE = "BROKER_NOMINEE",
  INTERMEDIARY = "INTERMEDIARY",
}

export enum PlanTimeHorizon {
  UNKNOWN = "UNKNOWN",
  LESS_THAN_YEAR = "LESS_THAN_YEAR",
  BETWEEN_1_AND_3_YEARS = "BETWEEN_1_AND_3_YEARS",
  BETWEEN_3_AND_5_YEARS = "BETWEEN_3_AND_5_YEARS",
  BETWEEN_5_AND_10_YEARS = "BETWEEN_5_AND_10_YEARS",
  BETWEEN_10_AND_20_YEARS = "BETWEEN_10_AND_20_YEARS",
  MORE_THAN_20_YEARS = "MORE_THAN_20_YEARS",
}
