export enum currency {
  CAD = "CAD",
  USD = "USD",
}
export enum Gender {
  MALE = "M",
  FEMALE = "F",
  UNSPECIFIED = "X",
}
export enum DocumentType {
  UNKNOWN = "UNKNOWN",
  DRIVER_LICENSE = "DRIVER_LICENSE",
  BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE",
  PROVINCIAL_HEALTH_CARD = "PROVINCIAL_HEALTH_CARD",
  PASSPORT = "PASSPORT",
  PERMANENT_RESIDENCE_CARD = "PERMANENT_RESIDENCE_CARD",
  EMPLOYER_IDENTIFICATION_NUMBER = "EMPLOYER_IDENTIFICATION_NUMBER",
  TAXPAYER_IDENTIFICATION_NUMBER = "TAXPAYER_IDENTIFICATION_NUMBER",
  SOCIAL_SECURITY_NUMBER = "SOCIAL_SECURITY_NUMBER",
  OTHER = "OTHER",
}
export enum ClientFatcaCrsNoTinReason {
  UNKNOWN = "UNKNOWN",
  CLIENT_NOT_RECEIVED_TIN = "CLIENT_NOT_RECEIVED_TIN",
  JURISDICTION_DOES_NOT_ISSUE_TINS = "JURISDICTION_DOES_NOT_ISSUE_TINS",
  OTHER = "OTHER",
}
export enum CrsEntityType {
  UNKNOWN = "UNKNOWN",
  PASIVE_NON_FINANCIAL_ENTITY_WITH_REPORTABLE_CONTROLING_PPERSONS = "PASIVE_NON_FINANCIAL_ENTITY_WITH_REPORTABLE_CONTROLING_PPERSONS",
  CRS_REPORTABLE_PERSON = "CRS_REPORTABLE_PERSON",
  PASIVE_NON_FINANCIAL_EENTITY_THAT_IS_REPORTABLE_PERSON = "PASIVE_NON_FINANCIAL_EENTITY_THAT_IS_REPORTABLE_PERSON",
}
export enum FatcaEntityType {
  UNKNOWN = "UNKNOWN",
  ACTIVE_NON_FINANCIAL_FOREIGN_ENTITY = "ACTIVE_NON_FINANCIAL_FOREIGN_ENTITY",
  EXEMPT_BENEFICIAL_OWNER_FOREIGN_FINANCIAL_INSTITUTION = "EXEMPT_BENEFICIAL_OWNER_FOREIGN_FINANCIAL_INSTITUTION",
  CANADIAN_FINANCIAL_INSTITUTION = "CANADIAN_FINANCIAL_INSTITUTION",
  DEEMED_COMPLIANT_FOREIGN_FINANCIAL_INSTITUTION = "DEEMED_COMPLIANT_FOREIGN_FINANCIAL_INSTITUTION",
  EXCEPTED_FOREIGN_FINANCIAL_INSTITUTION = "EXCEPTED_FOREIGN_FINANCIAL_INSTITUTION",
  PASIVE_FOREIGN_FINANCIAL_INSTITUTION = "PASIVE_FOREIGN_FINANCIAL_INSTITUTION",
  PASIVE_FOREIGN_FINANCIAL_ENTITY_NFFE_WITH_NO_US_CONTROLIN_PERSONS = "PASIVE_FOREIGN_FINANCIAL_ENTITY_NFFE_WITH_NO_US_CONTROLIN_PERSONS",
  PASIVE_FOREIGN_FINANCIAL_ENTITY_NFFE_WITH_ONE_OR_MORE_US_CONTROLIN_PERSONS = "PASIVE_FOREIGN_FINANCIAL_ENTITY_NFFE_WITH_ONE_OR_MORE_US_CONTROLIN_PERSONS",
  PARTNER_COUNTRY_FINANCIAL_INSTITUTION = "PARTNER_COUNTRY_FINANCIAL_INSTITUTION",
  NON_PARTICIPATING_FOREIGN_FINANCIAL_INSTITUTION = "NON_PARTICIPATING_FOREIGN_FINANCIAL_INSTITUTION",
  PENDING = "PENDING",
  SPECIFIED_US_PERSON_F104 = "SPECIFIED_US_PERSON_F104",
}
export enum PersonalIncomeRange {
  UNDER_25000 = "Under $25,000",
  RANGE_25000_49999 = "$25,000 - $49,999",
  RANGE_50000_74999 = "$50,000 - $74,999",
  RANGE_75000_99999 = "$75,000 - $99,999",
  RANGE_100000_124999 = "$100,000 - $124,999",
  RANGE_125000_199999 = "$125,000 - $199,999",
  RANGE_200000_999999 = "$200,000 - $999,999",
  MILLION_AND_OVER = "$1 million and over",
  UNKNOWN = "Unknown",
}

export enum FundAccountStatus {
  NOT_SPECIFIED = "NOT_SPECIFIED",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}
// Fund Facts Document Type
export enum FundFactsDocumentType {
  NOT_SPECIFIED = "NOT_SPECIFIED",
  ALL = "ALL",
  SIMPLIFIED_PROSPECTUS = "SIMPLIFIED_PROSPECTUS",
  LONG_FORM_PROSPECTUS = "LONG_FORM_PROSPECTUS",
  SHORT_FORM_PROSPECTUS = "SHORT_FORM_PROSPECTUS",
  OFFERING_MEMORANDUM = "OFFERING_MEMORANDUM",
  INFORMATION_FOLDER = "INFORMATION_FOLDER",
  FUND_FACTS = "FUND_FACTS",
  PRESS_RELEASE = "PRESS_RELEASE",
  FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT",
  MRFP = "MRFP",
  ADDENDUM = "ADDENDUM",
  ETF = "ETF",
}

// Language
export enum Language {
  NOT_SPECIFIED = "NOT_SPECIFIED",
  ENGLISH = "ENGLISH",
  FRENCH = "FRENCH",
}
