
// Client Type Enumeration

export enum ClientType {
  INDIVIDUAL = "INDIVIDUAL",
  CORPORATION = "CORPORATION",
  ASSOCIATION_TRUST_CLUB_PARTNERSHIP = "ASSOCIATION_TRUST_CLUB_PARTNERSHIP",
  GOVERNMENT = "GOVERNMENT",
}

// Client Marital Status Enumeration

export enum ClientMaritalStatus {
  UNKNOWN_STATUS = "UNKNOWN_STATUS",
  UNKNOWN = "UNKNOWN",
  SINGLE = "SINGLE",
  MARRIED = "MARRIED",
  DIVORCED = "DIVORCED",
  WIDOWED = "WIDOWED",
  COMMON_LAW = "COMMON_LAW",
  SEPARATED = "SEPARATED",
}
// Client Title Enumeration
export enum ClientTitle {
  UNKNOWN = "UNKNOWN",
  MR = "MR",
  MRS = "MRS",
  MISS = "MISS",
  MS = "MS",
  DR = "DR",
  PROF = "PROF",
  COMPANY = "COMPANY",
  OTHER = "OTHER",
}

// Client Status Enumeration
export enum ClientStatus {
  UNKNOWN_STATUS = "UNKNOWN_STATUS",
  ACTIVE = "ACTIVE",
  ACTIVE_PROSPECT = "ACTIVE_PROSPECT",
  INACTIVE = "INACTIVE",
  DECEASED = "DECEASED",
  UNKNOWN = "UNKNOWN",
}
// Client Knowledge Enumeration

export enum ClientKnowledge {
  SOPHISTICATED = "SOPHISTICATED",
  GOOD = "GOOD",
  FAIR = "FAIR",
  UNKNOWN = "UNKNOWN",
}

// Client Delivery Status Enumeration
export enum ClientDeliveryStatus {
  MAIL = "MAIL",
  EMAIL = "EMAIL",
  E_STATEMENT = "E_STATEMENT",
  ELECTRONIC_DELIVERY = "ELECTRONIC_DELIVERY",
  UNKNOWN = "UNKNOWN",
}
// Client FATCA Eligibility Enumeration
export enum ClientFatcaEligibility {
  NON_REPORTABLE = "NON_REPORTABLE",
  REPORTABLE = "REPORTABLE",
  REFUSES_TO_RESPOND = "REFUSES_TO_RESPOND",
  UNKNOWN = "UNKNOWN",
}

// Client CRS Eligibility Enumeration
export enum ClientCrsEligibility {
  NON_REPORTABLE = "NON_REPORTABLE",
  REPORTABLE = "REPORTABLE",
  REFUSES_TO_RESPOND = "REFUSES_TO_RESPOND",
  UNKNOWN = "UNKNOWN",
}

// Document Type Enumeration
export enum DocumentType {
  UNKNOWN = "UNKNOWN",
  DRIVER_LICENSE = "DRIVER_LICENSE",
  BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE",
  PROVINCIAL_HEALTH_CARD = "PROVINCIAL_HEALTH_CARD",
  PASSPORT = "PASSPORT",
  PERMANENT_RESIDENCE_CARD = "PERMANENT_RESIDENCE_CARD",
  EMPLOYER_IDENTIFICATION_NUMBER = "EMPLOYER_IDENTIFICATION_NUMBER",
  TAXPAYER_IDENTIFICATION_NUMBER = "TAXPAYER_IDENTIFICATION_NUMBER",
  SOCIAL_SECURITY_NUMBER = "SOCIAL_SECURITY_NUMBER",
  OTHER = "OTHER",
}
// Client FATCA/CRS No TIN Reason Enumeration
export enum ClientFatcaCrsNoTinReason {
  UNKNOWN = "UNKNOWN",
  CLIENT_NOT_RECEIVED_TIN = "CLIENT_NOT_RECEIVED_TIN",
  JURISDICTION_DOES_NOT_ISSUE_TINS = "JURISDICTION_DOES_NOT_ISSUE_TINS",
  OTHER = "OTHER",
}
// CRS Entity Type Enumeration
export enum CrsEntityType {
  UNKNOWN = "UNKNOWN",
  PASIVE_NON_FINANCIAL_ENTITY_WITH_REPORTABLE_CONTROLING_PPERSONS = "PASIVE_NON_FINANCIAL_ENTITY_WITH_REPORTABLE_CONTROLING_PPERSONS",
  CRS_REPORTABLE_PERSON = "CRS_REPORTABLE_PERSON",
  PASIVE_NON_FINANCIAL_EENTITY_THAT_IS_REPORTABLE_PERSON = "PASIVE_NON_FINANCIAL_EENTITY_THAT_IS_REPORTABLE_PERSON",
}

// FATCA Entity Type Enumeration
export enum FatcaEntityType {
  UNKNOWN = "UNKNOWN",
  ACTIVE_NON_FINANCIAL_FOREIGN_ENTITY = "ACTIVE_NON_FINANCIAL_FOREIGN_ENTITY",
  EXEMPT_BENEFICIAL_OWNER_FOREIGN_FINANCIAL_INSTITUTION = "EXEMPT_BENEFICIAL_OWNER_FOREIGN_FINANCIAL_INSTITUTION",
  CANADIAN_FINANCIAL_INSTITUTION = "CANADIAN_FINANCIAL_INSTITUTION",
  DEEMED_COMPLIANT_FOREIGN_FINANCIAL_INSTITUTION = "DEEMED_COMPLIANT_FOREIGN_FINANCIAL_INSTITUTION",
  EXCEPTED_FOREIGN_FINANCIAL_INSTITUTION = "EXCEPTED_FOREIGN_FINANCIAL_INSTITUTION",
  PASIVE_FOREIGN_FINANCIAL_INSTITUTION = "PASIVE_FOREIGN_FINANCIAL_INSTITUTION",
  PASIVE_FOREIGN_FINANCIAL_ENTITY_NFFE_WITH_NO_US_CONTROLIN_PERSONS = "PASIVE_FOREIGN_FINANCIAL_ENTITY_NFFE_WITH_NO_US_CONTROLIN_PERSONS",
  PASIVE_FOREIGN_FINANCIAL_ENTITY_NFFE_WITH_ONE_OR_MORE_US_CONTROLIN_PERSONS = "PASIVE_FOREIGN_FINANCIAL_ENTITY_NFFE_WITH_ONE_OR_MORE_US_CONTROLIN_PERSONS",
  PARTNER_COUNTRY_FINANCIAL_INSTITUTION = "PARTNER_COUNTRY_FINANCIAL_INSTITUTION",
  NON_PARTICIPATING_FOREIGN_FINANCIAL_INSTITUTION = "NON_PARTICIPATING_FOREIGN_FINANCIAL_INSTITUTION",
  PENDING = "PENDING",
  SPECIFIED_US_PERSON_F104 = "SPECIFIED_US_PERSON_F104",
}

// Client Politically Exposed Person Enumeration
export enum ClientPoliticallyExposedPerson {
  UNKNOWN = "UNKNOWN",
  NO = "NO",
  YES = "YES",
}

// Gender Enumeration (derived from documentation)
export enum Gender {
  MALE = "M",
  FEMALE = "F",
  UNSPECIFIED = "X",
}

//Personal Income Ranges (derived from documentation)
export enum PersonalIncomeRange {
  UNDER_25000 = "Under $25,000",
  RANGE_25000_49999 = "$25,000 - $49,999",
  RANGE_50000_74999 = "$50,000 - $74,999",
  RANGE_75000_99999 = "$75,000 - $99,999",
  RANGE_100000_124999 = "$100,000 - $124,999",
  RANGE_125000_199999 = "$125,000 - $199,999",
  RANGE_200000_999999 = "$200,000 - $999,999",
  MILLION_AND_OVER = "$1 million and over",
  UNKNOWN = "Unknown",
}

