export enum DocumentTypeLevel {
  UNKNOWN = "UNKNOWN",
  CLIENT = "CLIENT",
  PLAN = "PLAN",
  FUNDTRANSACTION = "FUNDTRANSACTION",
  GICTRANSACTION = "GICTRANSACTION",
  TRUSTTRANSACTION = "TRUSTTRANSACTION",
  FUNDACCOUNT = "FUNDACCOUNT",
  DEPOSITCHEQUE = "DEPOSITCHEQUE",
}

export enum DocumentTypeStatus {
  UNKNOWN = "UNKNOWN",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}
